"""ATLAS Layer 1 — hash-pinned LLM summary cards.

Cards are optional, per-file summaries generated by one headless
``claude-sonnet-4-6`` call per changed file. They are never triggered by
``atlas.py scan`` (R4): generation is always an explicit, priced action.
Every card is pinned to the ``content_hash`` of the file it was generated
from (R1) — ``atlas_core.query``/``where``/``impact`` already annotate every
file hit FRESH/STALE by comparing ``cards.source_hash`` against the file's
current ``content_hash``; this module only ever *produces* that pin, it
never edits the read paths that consume it (``scripts/atlas_core.py``,
``scripts/atlas.py`` are TASK-002's territory).

R1 — Cards are claims; code is truth. A card is served with its FRESH/STALE
status, never silently, and a model failure or malformed response leaves the
database untouched for that file (atomic per-card write) rather than writing
a bad or partial card.
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import atlas_core as core  # noqa: E402

DEFAULT_MODEL = "claude-sonnet-4-6"
DEFAULT_TIMEOUT_SECONDS = 120
REQUIRED_CARD_FIELDS = {"purpose", "invariants", "gotchas", "entry_points"}
MAX_SOURCE_CHARS = 20000  # keep the per-call prompt bounded for very large files

CARD_PROMPT_TEMPLATE = (
    "You are generating a machine-readable summary card for one source file "
    "in a software repository, for use by other coding agents who have not "
    "read the file. Read the file content below and respond with ONLY a "
    "single JSON object (no prose, no markdown fences) with exactly these "
    "keys:\n"
    '  "purpose": one or two sentence string - what this file is for\n'
    '  "invariants": array of strings - rules callers must not violate\n'
    '  "gotchas": array of strings - non-obvious behavior, edge cases, footguns\n'
    '  "entry_points": array of strings - the public functions/classes/CLI '
    "commands other code should call into\n"
    '  "tokens_estimate": integer - your best estimate of this file\'s token count\n\n'
    "File: {path}\n"
    "```\n{content}\n```\n"
)


class CardGenerationError(Exception):
    """Raised for a single file's card generation failure; never propagates
    past the file it concerns — the caller catches this and moves on."""


def _cards_cmd(repo: Path, model: str, override: list[str] | None) -> list[str]:
    """Resolve the headless model invocation. Tests substitute a real (but
    fake) executable via ``override`` or ``autopilot.json -> atlas.cards_cmd``
    — the same pattern ``distiller.py`` uses for ``learning.distill_cmd`` —
    so the suite shells out to a stub script instead of ever calling a live
    model (§6 A3: fake model transcript, zero live calls)."""
    if override is not None:
        return list(override)
    try:
        data = json.loads((repo / "autopilot.json").read_text(encoding="utf-8"))
        cmd = data.get("atlas", {}).get("cards_cmd")
        if cmd:
            return [str(x) for x in cmd]
    except (OSError, json.JSONDecodeError, AttributeError):
        pass
    return ["claude", "-p", "--model", model, "--dangerously-skip-permissions"]


def call_model(prompt: str, cmd: list[str], timeout: int = DEFAULT_TIMEOUT_SECONDS) -> str:
    try:
        proc = subprocess.run(
            cmd, input=prompt, capture_output=True, encoding="utf-8",
            errors="replace", timeout=timeout,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise CardGenerationError(f"model unreachable: {exc}") from exc
    if proc.returncode != 0:
        raise CardGenerationError(
            f"model call failed rc={proc.returncode}: {proc.stderr[:500]}"
        )
    return proc.stdout


def parse_card_output(text: str) -> dict:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise CardGenerationError("model output did not contain a JSON object")
    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError as exc:
        raise CardGenerationError(f"model output was not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise CardGenerationError("model output JSON was not an object")
    missing = REQUIRED_CARD_FIELDS - data.keys()
    if missing:
        raise CardGenerationError(
            f"model output missing required fields: {sorted(missing)}"
        )
    return data


def _stringify(value) -> str:
    if isinstance(value, str):
        return value
    return json.dumps(value)


def _tokens_estimate(data: dict, source_text: str) -> int:
    raw = data.get("tokens_estimate")
    try:
        estimate = int(raw)
        if estimate > 0:
            return estimate
    except (TypeError, ValueError):
        pass
    return max(1, len(source_text) // 4)


def _candidate_files(con, only: str | None) -> list:
    rows = con.execute(
        "SELECT f.id AS id, f.path AS path, f.content_hash AS content_hash "
        "FROM files f LEFT JOIN cards c ON c.file_id = f.id "
        "WHERE c.file_id IS NULL OR c.source_hash != f.content_hash "
        "ORDER BY f.path"
    ).fetchall()
    if not only:
        return rows
    return [r for r in rows if fnmatch.fnmatch(r["path"], only) or fnmatch.fnmatch(Path(r["path"]).name, only)]


def generate_cards(
    repo: Path,
    only: str | None = None,
    model: str = DEFAULT_MODEL,
    max_n: int | None = None,
    cmd_override: list[str] | None = None,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
) -> tuple[int, int, list[str]]:
    """Generate/refresh cards for files whose content_hash no longer matches
    their card's source_hash (or that have no card yet). Returns
    (generated, failed, error_messages). Each file's write is a single
    INSERT-OR-REPLACE committed immediately after that file's model call
    succeeds — a killed run or a per-file failure leaves no partial card and
    does not block the remaining files (R4: everything else still works)."""
    repo = repo.resolve()
    con = core.connect(repo)
    core.init_schema(con)
    candidates = _candidate_files(con, only)
    if max_n is not None:
        candidates = candidates[: max(0, max_n)]
    cmd = _cards_cmd(repo, model, cmd_override)
    generated = 0
    failed = 0
    errors: list[str] = []
    for row in candidates:
        rel = row["path"]
        full = repo / rel
        try:
            text = full.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            failed += 1
            errors.append(f"{rel}: cannot read file ({exc})")
            continue
        prompt = CARD_PROMPT_TEMPLATE.format(path=core.slash(rel), content=text[:MAX_SOURCE_CHARS])
        try:
            output = call_model(prompt, cmd, timeout=timeout)
            data = parse_card_output(output)
        except CardGenerationError as exc:
            failed += 1
            errors.append(f"{rel}: {exc}")
            continue
        con.execute(
            "INSERT INTO cards(file_id, source_hash, generated_at, model, purpose, "
            "invariants, gotchas, entry_points, tokens_estimate) VALUES (?,?,?,?,?,?,?,?,?) "
            "ON CONFLICT(file_id) DO UPDATE SET source_hash=excluded.source_hash, "
            "generated_at=excluded.generated_at, model=excluded.model, purpose=excluded.purpose, "
            "invariants=excluded.invariants, gotchas=excluded.gotchas, "
            "entry_points=excluded.entry_points, tokens_estimate=excluded.tokens_estimate",
            (
                row["id"], row["content_hash"], core.now(), model,
                _stringify(data.get("purpose", "")), _stringify(data.get("invariants", [])),
                _stringify(data.get("gotchas", [])), _stringify(data.get("entry_points", [])),
                _tokens_estimate(data, text),
            ),
        )
        con.commit()
        generated += 1
    con.close()
    return generated, failed, errors


def stale_cards(repo: Path) -> list[str]:
    con = core.connect(repo.resolve())
    core.init_schema(con)
    rows = con.execute(
        "SELECT f.path AS path, c.source_hash AS source_hash, f.content_hash AS content_hash "
        "FROM cards c JOIN files f ON f.id = c.file_id "
        "WHERE c.source_hash != f.content_hash ORDER BY f.path"
    ).fetchall()
    con.close()
    return [
        f"{core.slash(r['path'])} STALE (card pinned to {r['source_hash'][:12]}, "
        f"source now {r['content_hash'][:12]})"
        for r in rows
    ]


def _repo_arg() -> Path:
    return Path.cwd()


def cmd_cards(args: argparse.Namespace) -> int:
    repo = _repo_arg()
    if not args.generate and not args.stale:
        print("atlas cards: specify --generate or --stale", file=sys.stderr)
        return 1
    exit_code = 0
    if args.generate:
        generated, failed, errors = generate_cards(
            repo, only=args.only, model=args.model, max_n=args.max,
        )
        print(f"cards generated: {generated}; failed: {failed}")
        for line in errors:
            print(f"atlas: cards: {line}", file=sys.stderr)
        if failed:
            exit_code = 1
    if args.stale:
        lines = stale_cards(repo)
        print("\n".join(lines))
    return exit_code


def register(subparsers: argparse._SubParsersAction) -> None:
    cards_p = subparsers.add_parser("cards", help="generate or list hash-pinned LLM summary cards")
    cards_p.add_argument("--generate", action="store_true", help="generate/refresh cards for changed files")
    cards_p.add_argument("--stale", action="store_true", help="list cards whose source_hash no longer matches")
    cards_p.add_argument("--only", help="glob restricting which files are (re)generated")
    cards_p.add_argument("--model", default=DEFAULT_MODEL, help=f"headless model to invoke (default {DEFAULT_MODEL})")
    cards_p.add_argument("--max", type=int, default=None, help="cap the number of files generated this run")
    cards_p.set_defaults(handler=cmd_cards)
